### ISSUE TITLE
tremfusion crashes with many maps

### ISSUE THREAD

**Issue by piotrturski** [Amanieu/tremfusion#1]
during startup tremfusion processes all maps in 'base' directory. when number of maps goes near the `ulimit -Sn` of the tremfusion process, the game crashes just after it was started. increasing ulimit permits adding more maps. it would be nice if tremfusion closed each map file after processing and opened it only when needed

**Comment by Amanieu** [comment]
This is due to how the quake 3 filesystem works, it will keep an open file handle for each pk3 in the game directory. If this is a problem for you then you should increase the ulimit for tremfusion. Changing the filesystem at this point is too much work considering the code hasn't been touched in the past 5 years.
